# Generated by Django 5.0.6 on 2025-05-12 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('marcaProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionProducto', models.TextField(blank=True, max_length=1000, null=True)),
                ('precioProducto', models.PositiveIntegerField()),
                ('stockProducto', models.PositiveIntegerField(default=0)),
                ('categoriaProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('portadaProducto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('requiere_envio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.order')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.producto')),
            ],
            options={
                'verbose_name': 'item de orden',
                'verbose_name_plural': 'items de orden',
            },
        ),
    ]
