# Generated by Django 5.0.6 on 2025-05-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('nombreProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('marcaProducto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionProducto', models.TextField(blank=True, max_length=1000, null=True)),
                ('precioProducto', models.PositiveIntegerField()),
                ('portadaProducto', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='tarjetacompra',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tarjetacompra',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.producto'),
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='TarjetaCompra',
        ),
    ]
