# Generated by Django 5.0.6 on 2025-05-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_orderitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Carrito activo'), ('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('despachado', 'Despachado'), ('entregado', 'Entregado')], default='carrito', max_length=20),
        ),
    ]
