# Generated by Django 5.0.6 on 2025-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_producto_remove_orderitem_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoriaProducto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_envio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
