# Generated by Django 5.0.6 on 2025-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_order_user_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
