# Generated by Django 5.0.6 on 2025-05-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_order_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
